### PR TITLE
add tests, noarch python

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi folks, thanks for maintaining this!

This attempts restoring windows builds... if that works, seems like there's no reason it shouldn't be `noarch`.

Note, regarding running the tests: I've made an [upstream PR](https://github.com/rmorshea/spectate/pull/48) to remove the `tests` package... keeping them might require grabbing the source at the published tag...

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/spectate ready for review! efb13d1 shows the thing working on windows, with the tests. i always forget to subtract one on the coverage threshold because rounding, but having it helps me :zzz: at night.

**Comment by marimeireles** [comment]
Seems good to me, I'll give it another day if there's anyone else interested in reviewing, but otherwise I'll merge it :)
Thanks for the work @bollwyvl!

**Pull request merged**
